### ISSUE TITLE
Property 'toHaveTextContent' does not exist on type

### ISSUE THREAD

**Issue by victorkink** [bartstc/spa-vite-template#1]
Hey @bartstc, thanks for the great template!
Unfortunately when I ran the `pnpm dev` command I get the following error:
```
    ERROR(TypeScript)  Property "toHaveTextContent" does not exist on type "JestMatchers<HTMLElement>".
    /path-to-project/App.stories.tsx:28:33

    26 |   await userEvent.click(incrementButton);
    27 |
    28 |   await expect(incrementButton).toHaveTextContent("count is 1");
       |                                 ^^^^^^^^^^^^^^^^^
    29 | };
    30 |
```

**Comment by bartstc** [comment]
Hi, thanks for the feedback. At this point, this template supports the `yarn` package manager and I didn't test its DX with `pnpm`. But I am about to replace `yarn` with `pnpm` in the near future I hope.

I encourage you to try `yarn` and check if the same problem will occur. I have already tested it both in dev container as well as locally and everything works just fine.

I believe you may always experience some undesired problems regarding the different setups of the environment like node version etc. That's why I configured dev container in order to make it all smooth.

Let me know if trying `yarn` or devcontainer helped. If not, please provide more details about your setup and the path you were following to run this project next time.

Thanks!

**Comment by victorkink** [comment]
Yep, installing dependencies with `yarn` fixed it and now works like a charm.

Thanks for your response!
